apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-now-app.name" . }}
  labels:
    app: {{ include "go-now-app.name" . }}
spec:
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "go-now-app.name" . }}
